### ISSUE TITLE
Broken migration

### ISSUE THREAD

**Issue by jgonggrijp** [devkral/rdflib-django3#2]
I'm using a Python 3.4.9_1 virtualenv with Django 1.11.18 and rdflib 4.2.2 in which I installed rdflib-django3 version 0.2.3. I added `'rdflib_django'` to the `INSTALLED_APPS` setting. When trying to run the migrations, I got the following output:

```console
$ python manage.py migrate
  Applying rdflib_django.0001_initial... OK
  Applying rdflib_django.0002_auto_20181112_1317...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File ".env/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File ".env/lib/python3.4/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".env/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".env/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File ".env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File ".env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File ".env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File ".env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File ".env/lib/python3.4/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File ".env/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 221, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File ".env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 531, in alter_field
    old_db_params, new_db_params, strict)
  File ".env/lib/python3.4/site-packages/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File ".env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 634, in _alter_field
    old_default = self.effective_default(old_field)
  File ".env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 245, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File ".env/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save
    prepared=False)
  File ".env/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 762, in get_db_prep_value
    value = self.get_prep_value(value)
  File ".env/lib/python3.4/site-packages/rdflib_django/fields.py", line 107, in get_prep_value
    return serialize_uri(value)
  File ".env/lib/python3.4/site-packages/rdflib_django/fields.py", line 82, in serialize_uri
    value, value.__class__)
ValueError: Cannot get prepvalue for None of type <class 'NoneType'>
```

Workaround suggestions welcome!

**Comment by devkral** [comment]
I think it is an issue with an other behaviour of postgrsql. I tested only with sqlite3.

Thank you for your bugreport, I never noticed it

**Comment by devkral** [comment]
can you test again? I hope I fixed this bug.

**Comment by jgonggrijp** [comment]
Yes, the migration now runs without errors (if I clone the repo and `pip install -e` it locally). Thank you very much! 🚀
